# Generated by Django 5.2.3 on 2025-07-02 00:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participation', '0002_tag_opportunity_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('tag', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='summary',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
