# Generated by Django 5.2.3 on 2025-07-02 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participation', '0003_tagsubscription_alter_opportunity_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagsubscription',
            name='tag',
        ),
        migrations.AddField(
            model_name='tagsubscription',
            name='tags',
            field=models.ManyToManyField(to='participation.tag'),
        ),
    ]
