# Generated by Django 5.2.3 on 2025-07-08 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participation', '0005_tag_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='category',
            field=models.CharField(choices=[('project', 'project'), ('skill', 'skill'), ('interest', 'interest')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
