# Generated by Django 5.2.3 on 2025-07-09 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participation', '0006_alter_tag_category_alter_tag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='defunct',
            field=models.BooleanField(default=False),
        ),
    ]
